[project]
name = "name2gender"
version = "0.0.1"
description = "From name to gender."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deeplotx>=0.8.7",
    "name4py>=0.1.4",
    "gdown",
    "requests",
]
